### ISSUE TITLE
Summary and content are required fields

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#1]
I easily foresee someone wanting to create several draft pages at once, for example radiothon. We could require summary and content fields only when publishing the article.

**Comment by matthazinski** [comment]
Can we just get rid of 'content'? and make everything use the summary field?

**Comment by telnoratti** [comment]
Why don't we get rid of summary and make everything use the content field? =P

**Comment by matthazinski** [comment]
That probably makes more sense. Patches welcome :stuck_out_tongue:

**Comment by telnoratti** [comment]
Patches will come.

**Comment by mutantmonkey** [comment]
The reason summary is separate is because someone might want to have a shorter version of the article on the homepage, without displaying the whole thing; it wasn't put there "just because." I strongly advise against removing this useful functionality.

**Comment by matthazinski** [comment]
IIRC this functionality is currently broken somewhere. (I don't remember where though).

**Comment by matthazinski** [comment]
Marking as WONTFIX. If we find any issues with summary/content we can open new bugs.
