### ISSUE TITLE
Increase max length of pages/articles

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#10]
The max length is insufficient, as seen here http://128.173.235.22/alumni

**Comment by mutantmonkey** [comment]
I specified a length for the UnicodeText columns in cb3a68569e754cd9dc998941c77b88450e1f7788; I think this is because you hit the limit for MySQL's TEXT data type. You'll have to manually alter the existing column to be LONGTEXT.

**Comment by matthazinski** [comment]
I updated the database and it seems to have fixed the issue.
