### ISSUE TITLE
Not enough spacing between bullets and images

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#100]
Examples:
- https://www.wuvt.vt.edu/local-zone
- https://www.wuvt.vt.edu/community

**Comment by bkodres93** [comment]
css confuses me

**Comment by mutantmonkey** [comment]
Define "not enough spacing." Do you mean you want list items to be indented so that the bullet is flush with the left margin of the text?

If so, note that no word processor agrees with you, not Word, not LibreOffice, not LaTeX. :P

**Comment by mutantmonkey** [comment]
Another option could be to simply add more right padding to the images, which I think might be a better option here.

**Comment by telnoratti** [comment]
Note that on localzone currently the numering overlaps the image. 
![localzoneoverlap](https://cloud.githubusercontent.com/assets/599870/18221006/be91ee54-7145-11e6-840d-a9e3989d74dd.png)

**Comment by mutantmonkey** [comment]
As discussed on IRC, we went with an alternative fix in faa0c185e00ee5a0f368288b71c9e4e666c66898.
