### ISSUE TITLE
Artist, album, track statistics pages

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#101]
On any set page (or last15), it would be nice if you could click on an album, artist, or track and see:

- [x] All instances in which that album/artist/track was ever played and the associated DJ and datetime
- [ ] Number of times the album/artist/track was played in the past week/month/year/ever
- [ ] Top n DJs that have played the track 
- [ ] (For artists), similar artists using last.fm's API. This would need to be cached in the DB so we don't exceed API request limits

**Comment by telnoratti** [comment]
This feature should be merged with #68

**Comment by matthazinski** [comment]
I imagine this one would be for public-facing things and #68 would be trackman-internal.

**Comment by echarlie** [comment]
we display how many times a track was played ever, and link to musicbrainz where possible. I think this is substantially complete and should be broken into more approachable issues.
