### ISSUE TITLE
Trackman autocomplete using other metadata sources

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#102]
A DJ should be able to enter a track by searching for artists/albums on one of several options:
1. MusicBrainz (they offer a [PostgreSQL data feed](https://musicbrainz.org/doc/Live_Data_Feed) but we could also use their API if we don't anticipate heavy usage)
2. Tracks historically entered into Trackman (already implemented)
3. Our library (currently using the Excel->SQL tool)
4. Our future library (some tool yet to be determined)
5. Discogs (they offer both an [API](http://www.discogs.com/developers/) and monthly data dumps).

Enabled metadata sources should be configurable in config.py, along with any API keys or site-specific URIs.

Trackman MUST NOT modify the library database in any way. Trackman's DB may refer to items in the library via internal or MusicBrainz IDs, but they should not be otherwise linked.

The UI of this should function as follows: 
- There are four sections from top to bottom:
  - Playlist (already played tracks)
  - Play queue (not yet played tracks)
  - Input boxes (for the DJ to type in any field)
  - Search results
- The search results should have a tabbed display (bootstrap's tab.js) for each of the different metadata sources. 
- A user enters text in the input boxes and search results are fetched in real time. The user can switch between tabs without having to re-input text.
- On each tab, there are buttons to queue and add tracks. Clicking either button does NOT clear the search results or search entry; this must be done manually as specified in #37.
- The tab currently displayed to the user should not change unless the user clicks on a different tab.

Search should be implemented under the assumption that it will eventually be made available through an internal API (restricted to internal IPs).

**Comment by telnoratti** [comment]
This will require significant schema changes. I'm not quite sure how this should be done yet. It's possible we will link each track to a mbid and libraryid distinctly. Adding a track from MB will likely dupe it.

**Comment by telnoratti** [comment]
Another issue with this is when viewing the MusicBrainz tab there may not be results for a track, but it has been previously entered. How do we communicate to the user that they should be looking at that instead of entering it as a new track, since not using the previously entered track will result in a duplicate?

**Comment by matthazinski** [comment]
You could grey-out tabs that don't contain any results.

**Comment by telnoratti** [comment]
I don't think that's obvious enough. If I'm finding results for everything at once anyways, perhaps we should have a way to display them together.

**Comment by mutantmonkey** [comment]
I am certain there will be many tracks that WUVT plays that there will be no MusicBrainz results for. One thing we might investigate is if submitting data programmatically to the MusicBrainz database is allowed by their API...that way WUVT could give back to the MusicBrainz community.

**Comment by telnoratti** [comment]
I doubt it. I've contributed a bit and we aren't entering enough information to be considered a valid entry.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#6
