### ISSUE TITLE
Fix SSL on engine

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#104]
https://engine.wuvt.vt.edu/ has a broken cert, which gives mixed content warnings.

**Comment by mutantmonkey** [comment]
Well technically the reason for the mixed content warning is that the stream doesn't play over HTTPS, but yes, that is why that is.

**Comment by matthazinski** [comment]
There's no SSL currently so this is irrelevant. Closing as WONTFIX.

**Comment by mutantmonkey** [comment]
This is an issue that needs to be fixed. It causes mixed content warnings.

**Comment by matthazinski** [comment]
There's no HTTPS support at all, so this issue currently makes no sense. Open a new Jira ticket if you want HTTPS implemented.
