### ISSUE TITLE
Asynchronously update metadata endpoints

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#105]
Updating last.fm, libre.fm, icecast, and tunein should happen asychronously in log_track instead of introducing lag into the trackman interface.

**Comment by matthazinski** [comment]
:+1:

**Comment by telnoratti** [comment]
Should be implemented along side #89

**Comment by mutantmonkey** [comment]
Fixed in 0ae5b14d5d6f0c0d2d82b79babdc8097ed1175ef and confirmed to be working.
