### ISSUE TITLE
Top nav menu items should be pinnable

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#106]
There are some menu items in the top navigation that may not fit into the rest of the items in the list; for example, the schedule under the shows menu.

It should be possible to set a "pinned" flag on each menu item. Pinned items will appear first in alphabetical order, followed by the rest of the items, also in alphabetical order.

**Comment by mutantmonkey** [comment]
Targeting for 2.0 because it requires a schema change.

**Comment by echarlie** [comment]
wontfix: navigation changed.
