### ISSUE TITLE
Article preview uses summary rather than content field

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#109]

**Comment by mutantmonkey** [comment]
What if you want to preview the summary though?

**Comment by telnoratti** [comment]
Should we get rid of the summary? No one uses it.

**Comment by mutantmonkey** [comment]
It is used. We should have the preview display the content though.

**Comment by echarlie** [comment]
I checked, and it looks like this is fixed for articles. I'm closing.
