### ISSUE TITLE
Document deployment instructions

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#110]
The readme should include info on uwsgi, celery, etc.

**Comment by mutantmonkey** [comment]
This needs to be done after any major deployment changes are complete; I don't want to waste time on something that's out of date.

**Comment by mutantmonkey** [comment]
It doesn't make any sense to keep this open. The request is vague, it will require a considerable amount of duplicated effort to write this, and the Dockerfiles are already designed to make deployment easy.
