### ISSUE TITLE
Automation should not have a logged in session if a DJ is logged in

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#111]
![capture](https://cloud.githubusercontent.com/assets/599870/6702825/e7b9202e-cd07-11e4-9d2b-82cd4e2a7873.PNG)

**Comment by matthazinski** [comment]
:+1:

**Comment by telnoratti** [comment]
Best theory is that Trackman was open in two tabs. It seems that automation_enabled was set to false since no tracks were logged. dj_activity should check for open DJSets?

**Comment by mutantmonkey** [comment]
I think the change in b8e8817a122f95b0455f5ca15e3a09b8fc02bbcc may fix this issue.

**Comment by mutantmonkey** [comment]
All issues relating to set start/end times and multiple sets being open at once should be resolved now with b6790540c09954a76bb4dff7d56bc85d29137b33. If there are any more issues, please open a new issue.
