### ISSUE TITLE
Unified reporting feature

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#112]
There are many scenarios in which we'd like to have a semi-automated way to scold or punish people. Typically this would be DJs using Trackman incorrectly (bad metadata is a cardinal sin), but I imagine it may be necessary to expand to traffic staff as well.

I'd like a form that authenticated users (via LDAP groups) can fill out with a playlist ID and a drop-down list of common complaints, with support for a comments field.

This could have a number of different outcomes depending on whether this is a repeat offense, including:
- Email-based complaints to the individual or their staff head.
- Twilio integration to call the requests line or text DJs informing them of their mistakes
- For severe cases, trigger broadcast intrusion using our DASDEC. This has the advantage that there's nothing the DJ can do to override it.

This was partially inspired by [WUPHF](https://www.youtube.com/watch?v=ytc9-wGCHW0).

**Comment by telnoratti** [comment]
I think this is a required feature given the state of automation and track entry currently. These are unacceptable now that they're curating our track database. @benjaques will need to give input if we are going to have anything more than a slap on the wrist. I think bad track entry, for traffic staff or DJs should have an eventual punishment of losing air. When we integrate schedule this could automatically track absences as well.

**Comment by telnoratti** [comment]
As for the DASDEC feature, what would that look like?

**Comment by matthazinski** [comment]
We have root ssh on the DASDEC, just need to find a way to trigger the relays. Then we could play automation on that using OpenOB.

**Comment by mutantmonkey** [comment]
The linked YouTube video no longer works. Does anyone have a mirror?

**Comment by echarlie** [comment]
I'm inclined to say this is no longer a necessity.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#41
