### ISSUE TITLE
Schedule should be exportable in iCal format

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#122]
As a user, I would like the ability to easily add events to my calendar. An iCal export feature would make this easy. I'm not sure whether it would be best to offer an .ics file for each show, or for the entire schedule.

**Comment by matthazinski** [comment]
:+1: but this means we'd also have to implement the schedule programmatically and add interfaces to update it... I suppose this could be done in config.py.

**Comment by mutantmonkey** [comment]
Maybe the schedule could just be a Google Calendar or something similar?

**Comment by bkodres93** [comment]
tis a good calendar now.
