### ISSUE TITLE
Support CSV log import to trackman

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#123]
There should be a way to support importing a CSV (or tab-delimited) file into a Trackman queue. This would be convenient for DJs that plan their sets in advance like @andreimarcu.

**Comment by mutantmonkey** [comment]
a54db5338ecd5a0fc6592b701dd119fcdd65014f provides the frontend functionality to add items to the queue from JSON, and can be used from the browser's console immediately. CSV support will require backend functionality to accept uploaded CSV files and convert them to JSON, and a frontend interface for this to work.

**Comment by mutantmonkey** [comment]
Does anyone still want this or is the JSON functionality sufficient?

**Comment by matthazinski** [comment]
JSON should be sufficient for now but documentation in /rtfm/user-docs would be nice

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#37
