### ISSUE TITLE
RSS feeds appear broken

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#13]
The main RSS feed shows articles that it shouldn't. All RSS feeds are showing raw markdown instead of HTML.

**Comment by mutantmonkey** [comment]
This needs to be investigated by someone who isn't afraid to touch the database, i.e., not me. :P

**Comment by matthazinski** [comment]
Fixed in https://github.com/wuvt/wuvt-site/commit/eb24fad6499c3fe97f95b11a9ccd017d0dafa85f
