### ISSUE TITLE
FCC tagging of tracks

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#131]
Each track should have an additional boolean field to allow flagging it for containing FCC violations.
This should be set when adding a track, and allow flagging and maybe editing.

**Comment by matthazinski** [comment]
This will be very difficult to implement because:
1. It's not always apparent when a track is explicit - these aren't always marked.
2. We don't tag tracks any differently if they're the clean version
3. I'm worried people will interpret an un-set flag as meaning 'clean'

**Comment by mutantmonkey** [comment]
I don't think it makes sense to store this information in Trackman at all. Please reopen if you disagree and we can discuss this.
