### ISSUE TITLE
Trackman support for multiple machines

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#135]
Allow multiple computers to be used simultaneously for track logging to accommodate two DJs in one time slot. This requires the track queue to be stored server-side.

**Comment by telnoratti** [comment]
The main conceptual difficulty I see with this is when you queue a track you are saying that track is a valid entry. It could also lead to Tracks without plays which is something I didn't accomodate when writing it. As far as I know changing that assumption will not break anything but it needs to be visited.

**Comment by telnoratti** [comment]
Do we really need a unified queue for 2 DJs doing a show? Changing to maybe until we know if support isn't already implemented.

**Comment by mutantmonkey** [comment]
I don't really see any reason to store the queue server-side. If there are two DJs, why can't there be two queues? Presumably there's either going to be one person spinning, or if they're both spinning, they're going to trade off tracks.

**Comment by matthazinski** [comment]
I suppose for now we can just have two separate queues using DOM storage since moving it server side would be fairly involved. 

The main thing for this is to ensure that:
1. Trackman works with one DJ logged in simultaneously on multiple machines
2. Logging in on one machine logs out all other users on all machines
3. If one DJ logs in on a second machine, this should log to the same set as the first machine and not log out the first machine.

**Comment by telnoratti** [comment]
We will need a second sse endpoint to implement this (alerting other machines etc.)

Also I can't think of a non-kluge way to determine separate machine logins. I think by IP will possibly miss some cases.

**Comment by matthazinski** [comment]
Yeah, I wouldn't want to do it by IP. 

Maybe we should have a 'slave' trackman endpoint for all other computers that just adds to whatever DJ set is currently playing.

**Comment by telnoratti** [comment]
I trust DJs to fuck that up.

**Comment by mutantmonkey** [comment]
With 0c0113dea3fef3cd9f352941a6111d5d2e8e746b, we will now log out all sessions at once. The only aspect of this issue that is not covered is displaying tracks that were played on another machine. Is this something that we want to support, or is the current mode of operation fine?

**Comment by echarlie** [comment]
another practical use would be for DJs to queue tracks from their phones while in the stacks (if we added login or something).

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#38
