### ISSUE TITLE
Trackman should show common errors to assist in debugging

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#139]
Trackman should show error messages for the most common problems to assist in debugging, such as:
- Stream unreachable
- Last.fm unreachable

**Comment by mutantmonkey** [comment]
DJs have no need to know what's wrong. This is exactly what the logs are for, and it's not even going to be possible to report on situations that happen with Celery tasks on the web interface without adding some sort of synchronization structure, which is a ridiculous amount of overhead.
