### ISSUE TITLE
GitHub issues are worthless

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#141]
We should start using an issue tracker that's actually worth the trouble of using.

**Comment by matthazinski** [comment]
Assigning @mutantmonkey to migrate to Jira :smile:

**Comment by mutantmonkey** [comment]
I don't believe I have administrative access to JIRA, do I?

**Comment by matthazinski** [comment]
You should, if not login as 'admin' with the root pw

**Comment by mutantmonkey** [comment]
I'm not going to spend the time to do this. Either someone else will have to take it or we will continue using GitHub issues.

**Comment by matthazinski** [comment]
Closing as WONTFIX. If the code is in Github already I guess there's no point in using Jira for this.
