### ISSUE TITLE
Track editing functionality for users in "librarians" LDAP group

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#142]

**Comment by mutantmonkey** [comment]
I wrote initial support for this in 91c1c8831deda6fec6257d5d4525341ffb90d2e0. It's pretty basic right now and will probably need a bit of work before it's ready to merge into master.

Some questions regarding this:
* Should tracks that have the same artist, album, title, and label be merged? If so, should this be done at edit time or as a periodic Celery task?
* Do we think pagination will be necessary for this? This is probably going to be hard to judge without Quicktrack data imported at the moment.
* Do we want to have support for viewing track reports in the initial iteration of this, or should that be done later on?

**Comment by matthazinski** [comment]
> Should tracks that have the same artist, album, title, and label be merged? If so, should this be done at edit time or as a periodic Celery task?

Yes. I imagine a Celery task will be necessary for the QT import. 

> Do we think pagination will be necessary for this? This is probably going to be hard to judge without Quicktrack data imported.

With QT imported, YES. We can do a huge number per page though, maybe like 500

> Do we want to have support for viewing track reports in the initial iteration of this, or should that be done later on?

I'm not sure what you mean by this.

**Comment by mutantmonkey** [comment]
Regarding the track merging, please refer to 7bf323a9a3ff38df85ba5c9eff3ec12d7a26f4a6; the code is done, but needs review.

I added pagination in ab2921e3acf48f02e1d5c57a8a7c48d52ecbdda7.

DJs have the ability to report tracks with incorrect metadata. We need some mechanism to view the reports DJs have entered and deal with them accordingly. @telnoratti can probably explain more about this.

**Comment by mutantmonkey** [comment]
I'm going to go ahead and close this; we can use #144 to track the track reports.
