### ISSUE TITLE
Long artist/track entries can cause the DJ name to overflow

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#143]
![long_track_dj_overflow](https://cloud.githubusercontent.com/assets/67266/7214397/24541502-e59a-11e4-8fc8-8a0a388ef723.png)

**Comment by mutantmonkey** [comment]
This is going to be fairly involved to fix, since it needs to be fixed both for the initial static content load as well as dynamic updates.

**Comment by andreimarcu** [comment]
Or CSS...

**Comment by wad209** [comment]
Thanks andreimarcu.
