### ISSUE TITLE
/admin/library should allow filtering by flagged tracks

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#144]

**Comment by mutantmonkey** [comment]
I don't think this is the best approach, nor is it what @telnoratti had envisioned based on the discussions I've had with him. The idea was for DJs file reports of tracks with issues. These are dealt with in a ticketing system style, with the ability to view any notes that have been added.

**Comment by telnoratti** [comment]
I think the ticket style system should exist instead of this functionality. A search function should be supported though. We could probably copy a lot of code from trackman itself.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#15
