### ISSUE TITLE
/admin/library should allow filtering by automation/humans or any given DJ

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#145]
You should be able to optionally filter the artists/albums/tracks by things played by a specific DJ type (Automation/Humans/Either). 

This is because when an automation track is fixed it must also be fixed in the ID3 of the source file.

I'd also like the capability to browse by tracks entered by any DJ. Some are notorious for bad capitalization.

**Comment by mutantmonkey** [comment]
With 413d1e447979922259469e87b8f684aeee931a8a, it's now possible to see who played a specific track and at what time.

Filtering tracks is going to result in some pretty resource-intensive queries, I suspect. What is the benefit over what's already on the site now?

**Comment by matthazinski** [comment]
For arbitrary DJs: it would allow you to easily edit tracks by someone known for being inconsistent with track naming

For automation: this is necessary so you can efficiently edit tracks incorrectly logged by automation. This requires the user to take the extra step of tracking down the MP3 and editing the ID3 tag on the file server.

**Comment by echarlie** [comment]
Do we not have this feature, now?

**Comment by mutantmonkey** [comment]
I think the idea of this was to filter tracks that were initially logged by a particular DJ and provide the same artist/label/etc. interface. I think what we have now is good enough but we may want to add a note when editing a track that was logged by automation that the metadata will need to be updated in the file. Thoughts on that, @matthazinski? We can also potentially store any track edits and use those as sort of an "autocorrect" going forward, but that's going to be a lot of data to keep around.

**Comment by echarlie** [comment]
Since we have adequate coverage of the adjacent problem @mutantmonkey mentioned, I'm closing this.
