### ISSUE TITLE
/admin/library should make it easy to merge artists with different capitalization

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#146]
Not sure how this should be implemented, but it's currently not clear on /admin/library whether a given artist contains variations in capitalization. Maybe we should allow filtering by artists that contain multiple capitalizations?

Example:
https://www.wuvt.vt.edu/admin/library/artist?artist=Drake
https://www.wuvt.vt.edu/admin/library/artist?artist=drake

**Comment by mutantmonkey** [comment]
What is merging an artist? Do you want the ability to update all tracks that collate to the same thing to be updated simultaneously?

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#16
