### ISSUE TITLE
Auditing of edited tracks in /admin/library

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#149]
It would be nice if there was some database (or machine-parseable log) that indicated for each track edit:
- The user who edited it
- The first DJ to log the track (as he is responsible for the error) as well as the datetime it was first logged
- The track ID
- Whether or not it was flagged

This would allow us to get some metrics of most productive librarian staff and DJs bad at logging

Eventually we could use this to generate reports by DJ and send complaints to the appropriate person.

**Comment by mutantmonkey** [comment]
Well, the access logs will have some of this information, but yes, more detailed logging would be better.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#17
