### ISSUE TITLE
QT->Trackman import tools

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#15]
Import QT data into trackman

**Comment by telnoratti** [comment]
Is this still worthy of a deployment tag?  Qt data can't get imported before then.

**Comment by matthazinski** [comment]
'deployment' was intended to refer to things that aren't strictly dev tasks. The v1.0 milestone is what's used to refer to the actual deployment date.

**Comment by telnoratti** [comment]
#78 May be a prerequisite of this.

**Comment by matthazinski** [comment]
Can you elaborate on why #78 is a prereq? I think we just need to (manually) make a mapping of QT accounts to trackman accounts.

**Comment by telnoratti** [comment]
If #78 requires changing the scheme to have separate tables for DJs and Shows it will require more complex mappings. Especially since we're likely to encounter that situation during the import.

**Comment by telnoratti** [comment]
Current import plan involves:
1. Select a track
2. Compute a damerau-levenshtein distance formula to find typos of artist (distance 3 seems to work well)
3. Identify the primary artist (one with greater number, preferably a 2:1 ratio at least)
4. Compare if any of the similar artist names share an album with distance of 3
5. Merge all artists that share an album with the primary.
6. Flag remaining discrepant artists for manual intervention, record primary artist in the group, and place in separate table
7. Move primary and corrected tracks to second stage table
8. Remove all tracks from original table

**Comment by mutantmonkey** [comment]
Please create a separate issue for any future work.
