### ISSUE TITLE
editing a track and editing it back in trackman will result in duplicate tracks

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#150]

**Comment by mutantmonkey** [comment]
Hey now, this was directed at @telnoratti, but sure, I can work on this later. I think more importantly 7bf323a9a3ff38df85ba5c9eff3ec12d7a26f4a6 should get looked at, so these duplicates can be cleaned up.

**Comment by mutantmonkey** [comment]
So, this isn't really a major issue now that were are automatically pruning duplicates, but this would be pretty easy to do by just checking against the DB before creating a new track.

**Comment by mutantmonkey** [comment]
This should be pretty easy actually; we really should have gotten to it now.
