### ISSUE TITLE
"Automation On" button didn't send metadata to the website

### ISSUE THREAD

**Issue by jmc529** [wuvt/wuvt-site#152]
Ben & I ended our show and turned on automation through tracklogger, but the website hasn't updated the current dj to automation or uploaded any of automation's tracks.

**Comment by telnoratti** [comment]
send_metadata.py doesn't start on boot. This still needs to be fixed. I've started the script and there are metadata is still not updating the send_metadata.py is expecting a JSON response from trackman and doesn't recieve that.

**Comment by telnoratti** [comment]
Had to make an /etc/hosts change since the default site is not wuvt and changed the script to post to www.wuvt.vt.edu. This should be reflected in the repo, but I don't have time.
