### ISSUE TITLE
Trackman 2.0: Overhaul UI

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#159]
As promised in #158:

Trackman's UI should be updated to support additional use cases -- namely, users that are not the current DJ and becoming a unified DJ console It should consist of two main views: the login screen (using LDAP auth) and an interface for logged-in users. The latter should use a navbar like in /admin, and should include the following pages:
- Welcome panel, which includes:
  - A banner indicating what show, if any, is currently in progress 
  - A list of their shows, with "edit" and "DJ" buttons next to them. If one is in progress, it should be highlighted. If you click "DJ", you should be warned that it will end the show of whoever is in progress.
  - A "new show" button (equivalent to the 'register' functionality)
  - If the user is in TRACKMAN_ADMIN_GROUPS, a list of ALL other shows, with "edit" buttons next to them.
- Edit historical trackman tracks (functionality currently in /admin/library) 
- Playlist view - edits the playlist of the current show (what trackman currently does). If your user does not have access to the current user's show, this will be read-only and show a banner informing the user of this fact, with a link to go to the 'welcome' screen to start a new show by force. In the event a user's show ends due to timeout or another user starting a new show, an error banner should be displayed using SSE informing him of this fact.
- Teleprompter view - for convenience reading PSAs, UA, and other traffic. Write access restricted by LDAP groups to PR/Sales staff, etc. Each traffic piece has a 'log' button for the DJ to mark that it was read. Read access to the teleprompter is available without login, but you may not log traffic if you are not the show in progress. We'll need to figure out a usable UI for this later.
- Library - read access to searching our excel sheets

Each tab is only displayed if the user has at least read access to that functionality by being in the correct LDAP group.

This must be able to handle multiple simultaneous users (but only one active show) and multiple clients per user with no side effects. 

The user would do the following under normal circumstances:
1. Login screen - enter LDAP credentials, hit 'login'
2. Get presented with a welcome screen
3. Click "DJ" next to a show, and be taken to the typical trackman logging page. If there is another show in progress (other than automation), this should prompt the user to confirm that they want to end the current user's show.
4. Click "Logout" and be logged out entirely. (There should also be a less-obvious button in the footer to return to the welcome screen after ending a show)

**Comment by mutantmonkey** [comment]
I'd like to do some mockups for the UX of this, since this is pretty important to get right. A few DJs have had issues with Trackman as it is.

**Comment by bkodres93** [comment]
I can and would like to be a part of this.

**Comment by bkodres93** [comment]
@mutantmonkey I think it would definitely be good to separate shows and DJs
not quite sure how the UI would look for that, but it would be good if you could check off who is DJing a show if you have a guest or something, etc.
so both would get credit
if you have two people DJing together

**Comment by echarlie** [comment]
A thought: in step (3) don't start a DJ's show until they log their first track; they should be able to idle on the trackman interface, queueing tracks, without ending the prior show.

**Comment by mutantmonkey** [comment]
That is going to require significant refactoring of the automation handling and autologout code, just FYI.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#8
