### ISSUE TITLE
CAS support

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#160]
Implement CAS with an LDAP backend

**Comment by telnoratti** [comment]
What would CAS get us over just using the ldap backend? Conceivably in the future using just LDAP we could modify the LDAP tree from the admin interface. If we were to use CAS that would be much more complicated as far as I understand CAS.

**Comment by mutantmonkey** [comment]
I mean using CAS is going to require LDAP anyway, because CAS only provides the username. I don't really see any benefit to this since the website is basically the only thing that uses LDAP auth anyway. CAS would be useful with a bunch of separate services.

**Comment by telnoratti** [comment]
CAS is bad. It shouldn't be trusted anymore than actually giving them your
password. It can silently get a proxy ticket (equivalent to a TGT in krb
world).

**Comment by mutantmonkey** [comment]
@telnoratti proxy tickets don't have to be enabled.

**Comment by telnoratti** [comment]
Sure, but the user doesn't know if they are or not.

**Comment by mutantmonkey** [comment]
I'm not going to do this.

**Comment by matthazinski** [comment]
Closing for now as WONTFIX since this requires infrastructure changes. If someone wants to deploy Shibboleth on auth (LAN+WAN) we could reopen a ticket for acting as a SAML service provider.
