### ISSUE TITLE
Editing the last track should update track metadata on various services.

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#161]

**Comment by mutantmonkey** [comment]
Are there any services that actually support updating the metadata? I know with Last.fm, at least, there's no way to do this; you just have to scrobble it as a new track. TuneIn seems to keep a track history, so I could see that being problematic as well.

Anyway, with SSE this would require some refactoring as well and it can get a little messy. I'm not really sure it's worth the trouble.

**Comment by mutantmonkey** [comment]
I think I should make the appropriate tweaks to SSE (and Icecast too, probably) for this, but it's not going to work for other services.
