### ISSUE TITLE
Add twitter/facebook live feed to homepage

### ISSUE THREAD

**Issue by bkodres93** [wuvt/wuvt-site#169]
an idea for an addition

**Comment by bkodres93** [comment]
<img width="1393" alt="screenshot 2015-09-21 13 47 53" src="https://cloud.githubusercontent.com/assets/5027585/9999988/6b799dd8-6067-11e5-83c9-0ab81311dedb.png">
<img width="1387" alt="screenshot 2015-09-21 13 48 00" src="https://cloud.githubusercontent.com/assets/5027585/9999989/6b7a6a7e-6067-11e5-925f-cc43c50315fc.png">

**Comment by mutantmonkey** [comment]
I am very much against giving Twitter the ability to execute arbitrary JavaScript on the site. We should use Twitter's API and generate our own HTML for this.

**Comment by bkodres93** [comment]
@mutantmonkey word

**Comment by bkodres93** [comment]
What do you think: Twitter or Facebook?

**Comment by mutantmonkey** [comment]
I'd prefer Twitter personally, Facebook stuff might get a bit too long.

I think it might be a good idea to incorporate this as part of a larger homepage redesign. I was envisioning a frontpage with the latest weekly charts, perhaps the most recently played songs, and one news entry. That should leave a good bit of room for the feed.

**Comment by mutantmonkey** [comment]
Sorry for the lack of attention on this. I'd like to get the front page redesign done soon, please see that ticket for ideas.

**Comment by echarlie** [comment]
wuvt's twitter has not been that active, and I don't think facebook provides public visibility to allow us to include a live feed. instagram may be worthwhile, but by-and-large I dislike the idea of pointing to these walled garden services. Closing for now.
