### ISSUE TITLE
Move radiothon.collegemedia.com form to website

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#17]
This is horrendous: http://radiothon.collegemedia.com/
We should not be sending our users to a non-SSL third party site if we can avoid it

**Comment by mutantmonkey** [comment]
All tasks related to adding donation functionality into the main website should be merged into one, and I'll take care of this. I mainly need the business questions about this answered, like whether or not Stripe will be used and if that's going to be in addition to or instead of PayPal.

**Comment by matthazinski** [comment]
Moved to 'maybe' for that reason.

**Comment by mutantmonkey** [comment]
The new donation support was done months ago but we forgot to close this.
