### ISSUE TITLE
Pledges should not be marked as paid by default unless they were made with stripe

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#175]

**Comment by mutantmonkey** [comment]
We need an admin UI for this then. @telnoratti, do you want to implement that, and if so, should we get that done before this?

**Comment by matthazinski** [comment]
An admin UI to mark as paid is a separate issue. The core issue here is that donations are marked as paid when they aren't necessarily.

**Comment by mutantmonkey** [comment]
Sure, but right now there's no way to mark these donations as paid, period. I'd like to know the best course going forward. Should there be a paid checkbox that mission control can select when taking a pledge, or should that be handled separately?

**Comment by matthazinski** [comment]
I'd go with a checkbox at pledge time.
