### ISSUE TITLE
Front page redesign

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#177]
The front page should be redesigned because the current blog format is not working well. I definitely think we should include at least the last 5 tracks played, perhaps album art for the current now playing song (if we can find a good source), and also include Twitter as suggested by @bkodres93 in #169.
## Ideas
- [KALX](http://kalx.berkeley.edu/) incorporates charts directly into the homepage, which I really like.
- [KCPR's design](http://kcpr.org/) is interesting and has some good ideas, but it still has a lot of blog content that staff probably won't be updating.

**Comment by matthazinski** [comment]
:+1: to charts. One that would be interesting is top tracks by spins for the rolling week (not played by automation) that are in the "new music" rotation bin.

If the front page is redesigned, the template should be configurable in config.py.

**Comment by mutantmonkey** [comment]
> If the front page is redesigned, the template should be configurable in config.py.
What do you mean by this?

**Comment by mutantmonkey** [comment]
A carousel would probably work well for things on the front page, since most of the articles that get posted have associated pictures anyway.

**Comment by matthazinski** [comment]
>> If the front page is redesigned, the template should be configurable in config.py.
> What do you mean by this?

I meant an option in the config to switch between Jinja2 templates.

**Comment by echarlie** [comment]
This is a perenial topic. Closing until we have actionable design
