### ISSUE TITLE
Don't allow people to buy premiums if it's not radiothon

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#18]
Have a 'radiothon mode' which determines if we are able to sell premiums via the site. Else, tell people to email wuvtamfm instead.

**Comment by mutantmonkey** [comment]
We currently have two config options available; one for enabling "radiothon mode" and one for enabling the sale of premiums. Should these be merged or depend on the other?

**Comment by matthazinski** [comment]
They should be independent, in case someone wants to sell premiums at a different time.

**Comment by mutantmonkey** [comment]
This is done then.
