### ISSUE TITLE
Email DJs who forgot to logout

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#181]
When auto-logout is triggered, email the DJ with:
- A notification they have been auto-logged out
- A link to /rtfm/user-docs for more information on how to use Trackman

**Comment by mutantmonkey** [comment]
I think we should wait until the pre-autologout notification is in place before implementing this.

**Comment by mutantmonkey** [comment]
After some further analysis and discussion, the logout issue is clearly a problem; some DJs are getting logged out inadvertently, and others are just not logging out. Should we increase the logout delay and do this, or what?
