### ISSUE TITLE
Sets should store a bool to indicate if a recording is missing

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#183]
A celery task should run periodically to:
- Check the previous day's archive.org links (e.g. via the internetarchive python package) to ensure they are available
- Update the database to flag the item as unavailable if all recordings on IA were never uploaded
- If all recordings for an item were not available, optionally generate an error email

**Comment by matthazinski** [comment]
See also: #184 so these don't necessarily require emails.

**Comment by mutantmonkey** [comment]
We should probably also have a field for an offset in cases where the aircheck times were wrong.

**Comment by mutantmonkey** [comment]
Why should this be a feature of the site? Why shouldn't this be a separate application that provides notifications?
