### ISSUE TITLE
Trackman playlists should link to all relevant IA airchecks

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#19]
For a given playlist, link to all airchecks that cover any portion of the show as long as 15 minutes after the hour has passed (to allow time for uploading).

**Comment by telnoratti** [comment]
Are these the airchecks uploaded to archive? Couldn't it be possible to work with trackman record to a file whenever a dj is logged in? We could have it separate from aircheck that way it's dependant on the stream and not the air quality.

**Comment by matthazinski** [comment]
ALL airchecks are automatically uploaded to the Internet Archive. We could do streamrips too and also send those to IA, but that's another issue. I basically just want a given playlist (on the public site) to contain links to all airchecks that contain at least part of it. This would also include all historical playlists that eventually get migrated.

**Comment by telnoratti** [comment]
I was talking about self hosting the streams, but I suppose we could upload them to archive as well. It may be easier to make a distinction between new playlists and old ones anyways since there quicktrack doesn't separate a log from a track.

**Comment by matthazinski** [comment]
We can't self-host due to copyright issues... (we also don't have storage space for high-quality streams)

**Comment by telnoratti** [comment]
Okay fair enough. At any rate the simplest solution for now is the aforementioned linking to the correct archive.org link. See #26 for this feature

**Comment by telnoratti** [comment]
Tracks on archive.org are listed as https://archive.org/details/WUVTFM_YYYYMMDDHH. https://archive.org/details/WUVTFM_2015020917

How should we round the start time to match these hour formats? Sometimes DJs start at :30 instead of on the hours.

**Comment by matthazinski** [comment]
Include ALL airchecks that contain any portion of the DJ's show.
