### ISSUE TITLE
Embed google form for PSA's to Public Relations page

### ISSUE THREAD

**Issue by bkodres93** [wuvt/wuvt-site#192]
This contains three separate steps/requirements.
1. Most importantly, add "Submit PSA" to the red sidebar categories that takes one directly to the current Public Relations page.
2. Embed Joe Turner's google form (@telnoratti has access and can grab the embed html)
3. **Optional** -- remove the link under the Community tab that directs to the public relations page.
4. Reword the language on the Public Relations page so that it no longer gives people the option to download a pdf and go about the old-fashioned paper process. If they have stumbled upon the website, they could do to use the google form.

Joe Turner (Outreach Coordinator) has requested this be done, and I agree. Calvin has already approved the google form. Joe can be reached at joe5@vt.edu.

**Comment by telnoratti** [comment]
What is the frame size you want for embedding this?

**Comment by matthazinski** [comment]
I don't think any code changes are required for this. Assigning the webmaster.

**Comment by bkodres93** [comment]
@telnoratti I am not entirely sure what you mean by frame size, but I would assume the form should occupy the entire width of the space inside the surrounding section and be below whatever the new piece of writing is?

**Comment by telnoratti** [comment]
@bkodres93 We'll be embeding the form with an iframe, so you'll need to know dimensions you'll want for that. Do you really want it to occupy the entire width or do you want some margins?

    <iframe src="https://docs.google.com/forms/d/1Nbz7UJ0gfpJU_tL80-s65llM4_5zx8p36sPl7WQzjF0/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>

There's the iframe, I'll let you fiddle with it and decide what's best.

**Comment by bkodres93** [comment]
@telnoratti first i need to figure out how to run the site on OS X

**Comment by telnoratti** [comment]
You actually don't. You can create a new page copy the contents of the old page and then test using the new page. When you've gotten it where you need it to be, copy that page back into the old page. It might be worth putting in a feature request for previewing changes to a page in the future, but there's absolutely no requirement to run a second instance of the website.

**Comment by mutantmonkey** [comment]
@bkodres93 You should be able to get the site running in Docker on OS X. Refer to https://docs.docker.com/mac/step_one/ and the instructions on the homepage.

**Comment by echarlie** [comment]
this has been done. iframes are stupid and we should come up with a better way to do this, however.
