### ISSUE TITLE
Add privacy policy

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#194]
We should have a privacy policy to cover the following:

* Use of cookies on the website (session-only, for session and the CSRF token)
* Personal information collected during donations
* IP address, user-agent, and other information collected in logs

Anything else?

**Comment by telnoratti** [comment]
First draft
### Tracking information
This site uses cookies to track your progress through the site. This is for the site to operate correctly and isn't used to collect information on how you use the website. We do not use cookies to track you between uses of the website at different locations although using the same cookie may be used from multiple locations. We also use cookies to ensure no one is impersonating you when submitting data to the web page with CSRF tokens.

### Personal Information
We understand the value of your privacy and do not share any personal information gathered to third parties with the exception of Stripe. We use Stripe for payment processing and they require certain information. We also store some information gathered in the payment process separate from Stripe to track donations and make sure we can get donors their premiums. We will not reveal any personal information gathered to law enforcement or government without legal requirement to do so.

We also gather logs to help make the site better. Some of these are sent over unencrypted, but local email systems. Some of the information in the logs includes IP addresses, user-agent, and URL. This information is treated as personally identifiable information and only viewed as necessary and by authorized WUVT staff.

**Comment by mutantmonkey** [comment]
Merged this with 24b75a7
