### ISSUE TITLE
Emails occuring after auto-logout should be more passive aggressive

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#201]
Particularly for repeat offenders.

**Comment by echarlie** [comment]
do we want to have logic for several levels of passive-aggressiveness, based on some persistent data? I don't think it is important enough to justify the effort; it's become more and more of a non-issue compared to DJs just not knowing how to log

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#46
