### ISSUE TITLE
Auto-logout emails should have a configurable CC field

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#202]

**Comment by echarlie** [comment]
This should probably use the BCC field; I assume the intended use is to notify the FM PD or to open a JIRA ticket automatically. Should be pretty easy to do. Something to the extent of ```msg['BCC'] = current_app.config['AUTOLOGOUT_CC']``` around https://github.com/wuvt/wuvt-site/blob/master/wuvt/trackman/mail.py#L15 should do it, yes?

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#30
