### ISSUE TITLE
Add "Top by Rotation" to charts

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#203]
This is for some Purpose of Len's

**Comment by mutantmonkey** [comment]
Harrison really wants this feature, so it should happen soon.

**Comment by mutantmonkey** [comment]
@seanfmch Are you actively working on this, or should we change this back to unassigned for someone else to pick up?

**Comment by seanfmch** [comment]
@mutantmonkey sorry for holding it, I am not currently--If anyone wants it, feel free to go for it

**Comment by mutantmonkey** [comment]
No worries; I just wanted to update the status. Feel free to pick it back up again if you get a chance to work on it.

**Comment by echarlie** [comment]
This doesn't make sense in wuvt-site, and is mostly subsumed by https://github.com/wuvt/trackman/issues/110, anyway. Closing.
