### ISSUE TITLE
Add Alphabetic links to "Library" interface, to simplify searching for tracks to correct

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#204]
Search would be nice too. Page numbers as well, so I don't have to click [Next Page>] 200 times to get to the Zs.

**Comment by mutantmonkey** [comment]
Alphabetic links were added with 4fa508d423bc8bfa9584251491cdbf03b1918c62.

I opened #206 for search. If you still want page numbers, please open another issue. Please do not combine requests into a single issue because it makes tracking difficult.
