### ISSUE TITLE
Finish Trackman API

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#207]
Trackman's API is incomplete. While it is possible to achieve this functionality by making HTTP requests, these features are not part of the API and do not have responses that are useful for applications outside of a web browser. It may make sense to move the UI for these completely to the client side in order to avoid duplication of effort.

The following API calls should be added:
- [x] Create new DJSet ("login" although there isn't really any authentication)
- [ ] Start automation
  - This makes more sense as an API call anyway...
- [x] Report track
  - Since no one actually manages these, it might make sense for this feature to be removed.
- [x] End DJSet
  - Perhaps add an additional function for this that is called in both places.
  - The email playlist parameter is passed directly to this function currently, so the API will need to support this as well.

Register new DJ could also be a useful API call, but isn't really an important missing API feature.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#28
