### ISSUE TITLE
Trackman should fully replace engineering log 

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#21]
It would be extremely useful if trackman could allow people to indicate:
- When PSAs were read (and which ones)
- When underwriting was read
- When weather was read
- When station promos were read (and which ones)
- Transmitter readings
- Operator sign on/off times

This could replace the physical log book

**Comment by telnoratti** [comment]
It would be nice if trackman added engineering logs to the queue at the designated times.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#32
