### ISSUE TITLE
Create a thank you page

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#212]
We need page to list thank you's to supporters like VT departments and distinguished alumni etc.

**Comment by bkodres93** [comment]
does anyone have a list of who we are to be thanking and reasons for each, etc?

**Comment by telnoratti** [comment]
ECE, UGA, the guy who donated the optiplex, past 907 donors, etc.

**Comment by bkodres93** [comment]
is there a more formal list? and am I to list all 910 of them?

**Comment by telnoratti** [comment]
There have only been a few 907 donors, but just get those on the list for
now. We can add more later.

**Comment by bkodres93** [comment]
What specifically is the reason to thank the ECE department? And likewise
for UGA?

**Comment by telnoratti** [comment]
We just thank them for their support, no reasons.

**Comment by bkodres93** [comment]
What is the UGA?

**Comment by telnoratti** [comment]
@bkodres93 undergraduate admissions I don't understand what's so hard about this, draft up the design put in content, let us fill in the details as we have them

**Comment by bkodres93** [comment]
I wanted to make sure I didn't mistype something. And I have not gotten
around to it yet -- I will do it tomorrow.

**Comment by bkodres93** [comment]
www.wuvt.vt.edu/supporters
