### ISSUE TITLE
Add drag and drop to reorder tracks in the queue

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#231]
Currently, there is no way to reorder tracks in the Trackman queue. The best
way to do this is probably to simply add a handle so tracks can be dragged and
dropped to reorder them.

**Comment by echarlie** [comment]
I don't see the utility of this in trackman. it is definitely needed for live-assist.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#29
