### ISSUE TITLE
Site should validate existence of aircheck archives before linking them

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#233]
c.f. issue #183

**Comment by mutantmonkey** [comment]
So how is this actually going to work? We can't make these requests frequently, so we're going to have to store things somewhere. Is it really going to be worthwhile to store a link to every single archived recording in the database? I don't see much of a benefit.

**Comment by echarlie** [comment]
we can easily enumerate which airchecks are missing, but I agree this should not be part of the site.
