### ISSUE TITLE
"Report a Problem" feature in Trackman

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#235]
It would be convenient if we had an option for DJs to report engineering and IT issues directly from within Trackman.

From an implementation standpoint, we have two options:
* Embed an iframe to the JIRA service desk form. This method could make auth tricky, but would be simpler to implement.
* Have Trackman use the JIRA API to get the list of required fields and then create a ticket on the DJ's behalf. The benefit of this is that we can pull in the current DJ from Trackman with no way to override and we can use a single Trackman service account for JIRA.

**Comment by mutantmonkey** [comment]
I think JIRA collectors are the way to go. I believe this should be pretty easy; just some JavaScript to embed.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#9
