### ISSUE TITLE
Trackman should be able to operate offline

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#239]
To improve the user experience in the event of an outage or just flaky network connectivity, Trackman should make use of service workers and maintain a local list of tracks that have already been played. That way, if the Trackman API becomes unreachable, DJs can continue to log tracks as normal. When it becomes reachable again, the list of played tracks should be synchronized with the
server and maintain their existing timestamps.

Track search and autocomplete will initially be beyond the scope of this, but those are areas for future enhancement.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#40
