### ISSUE TITLE
Inconsistency in menu dropdowns

### ISSUE THREAD

**Issue by andreimarcu** [wuvt/wuvt-site#24]
## Exhibit A
In some cases, the top-level dropdown button is used as a classifier of sub-items (for example shows):
![screen shot 2015-03-01 at 4 57 31 pm](https://cloud.githubusercontent.com/assets/4650950/6433113/1136c568-c034-11e4-9c92-b9f987946049.png)

Under "SHOWS" appear different types of shows with articles for each one.

However, did you know that clicking SHOWS actually takes you to the schedule?

## Exhibit B
In other cases, the top-level item links to the first element of the dropdown:
![screen shot 2015-03-01 at 5 00 25 pm](https://cloud.githubusercontent.com/assets/4650950/6433132/79a4140c-c034-11e4-8472-ab9772d6894d.png)

When you click on PLAYLISTS, you're taken to BY DATE.

## Issue

I believe one or the other method should be decided.

Either you have a top-level item that does not link to anything but announces the type of links which can be found under it.  
Or you have a top-level item that has a page to itself, but in the case of SHOWS which goes to schedule, you need to somehow let that be known.

**Comment by matthazinski** [comment]
Fixed in https://github.com/wuvt/wuvt-site/commit/849941051007fc283da9189841c8caa348647403

**Comment by matthazinski** [comment]
Reopening because @andreimarcu was not happy with my fix.

**Comment by telnoratti** [comment]
@andreimarcu is invited to submit a pull request!

**Comment by matthazinski** [comment]
It's not a dev task, it can be fixed by staff in the admin panel.
