### ISSUE TITLE
dark mode theme for trackman

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#248]
as a DJ, I don't like when my eyes are burned out in the middle of a late-night show.

**Comment by mutantmonkey** [comment]
This would be good for someone with familiarity with Bootstrap. We can possibly leverage an existing dark Bootstrap theme or write our own. This shouldn't require any HTML changes, only CSS.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#11
