### ISSUE TITLE
Add OpenID Connect support

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#249]
We should add OpenID Connect support for integration with single sign-on systems. I'm not sure if we'll want to keep LDAP support around or just push people to this.

This could potentially also be useful for authenticating to the Trackman API.

**Comment by echarlie** [comment]
Yes. This could also be useful if someone wanted "comments" or some other interactive feature on the site.

**Comment by mutantmonkey** [comment]
Not really. We would probably restrict authentication either to our IdP or a specific Google Apps domain. Something like comments would use need to use different authentication entirely or we'd have to rework how authentication works.
