### ISSUE TITLE
Trackman log on/off times should trigger show recordings

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#26]
This is a potential better way to link to shows on the archive.org site.

**Comment by matthazinski** [comment]
So I assume the way this would function is:
- A DJ logs in, which triggers a streamrip to begin
- A DJ logs out, and the streamrip is stopped
- The streamrip is uploaded to IA and linked on the DJ's page. Trackman will need to know which item name is associated with each DJ. (That is, assuming each DJ has one item per show, which is easiest)

Some things to consider are:
- Why is the web server doing the stream rip? Why not have the stream server just provide an API to start/stop arecord? I'm concerned about icecast's buffering issues.
- Why bother passing through the Optimod in the first place? A computer in FM could provide uncompressed audio.

**Comment by telnoratti** [comment]
Trackman itself should not be doing the stream rip, but instead control the process. You're right though it should definitely not be run on the same machine as the webserver. Transcoding could be problematic as my bench-marking of the site's performance hasn't been promising.

There's a nasty edge case where DJs often log out before they're done, so we should keep recording until there's a song change or a new DJ logs in, not sure exactly.

**Comment by matthazinski** [comment]
Another thing: this should also send appropriate metadata (especially DJ name) to the IA as well so it's easier for people to find things. Ideally a playlist would be included too but I'm worried this would make it too attractive a target for DMCAs.

**Comment by mutantmonkey** [comment]
Dude, either it's a copyright violation or it's not. It makes no difference how hard it is to find.

**Comment by matthazinski** [comment]
it's harder for bots to find this way

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#33
