### ISSUE TITLE
Display username and auth source instead of full name in /admin/roles/users/add

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#261]
There are duplicate users and it's very confusing.

**Comment by mutantmonkey** [comment]
We probably want this on Pages as well.

**Comment by mutantmonkey** [comment]
This also isn't possible. We don't store the method.

**Comment by mutantmonkey** [comment]
This is currently happening on the main site because there are local users who were created with a username that doesn't match.
