### ISSUE TITLE
Show Scheduler

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#263]
We should have integrated show scheduling functionality. I'm thinking that there are really two things that need to be configurable: the time slots, which are only changed rarely, and the shows for each slot, which are changed basically every semester.

The default view should be the show scheduler, which should have a way in each time slot to either directly select a show there or access a page where show information can be entered. There should be an option to access the time slot configuration from this page, perhaps with a cog icon or something.

Shows should be able to have a DJ associated with them, but it should not be required. If there's a DJ associated with a show that starts in the next 15 minutes or has at least 15 minutes remaining, Trackman should suggest the show and provide a simple one-click login.

**Comment by echarlie** [comment]
Thoughts on migrating this to wuvt/trackman?

**Comment by mutantmonkey** [comment]
I would actually suggest that this might be best as a separate service.

**Comment by echarlie** [comment]
migrated to wuvt/it-tasks#23
