### ISSUE TITLE
chart ranking is broken: all items are #1

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#265]

**Comment by mutantmonkey** [comment]
This may have been caused by a library upgrade.

**Comment by mutantmonkey** [comment]
This is pallets/jinja#641. We may want to rework how the ranking works because apparently this wasn't supposed to work like this.

**Comment by echarlie** [comment]
broken again in the current release

**Comment by echarlie** [comment]
How do people feel about disabling ranking for now, outright?

**Comment by mutantmonkey** [comment]
We will not disable the ranking. A permanent fix for this is included in #298.
