### ISSUE TITLE
Allow whitelisting/blacklisting of allowed roles based on connector used with OIDC provider

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#267]
e.g. don't allow someone to assign admin role to a non-LDAP user

**Comment by mutantmonkey** [comment]
I think you mean you want this to depend on the connector used with the OIDC provider; we don't support multiple OIDC providers. That would depend on coreos/dex#831.

**Comment by echarlie** [comment]
we've stopped using a multi-connector oidc provider. closing until there's external interest.
