### ISSUE TITLE
Event calendar

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#277]
As a WUVT supporter, I would like an events calendar to be displayed prominently on the home page so that I can see upcoming events. It should be possible for anyone who organizes events at WUVT to update this calendar.

We can support a local calendar stored in the DB, an iCalendar feed, or both.

**Comment by echarlie** [comment]
making iCalendar support available to the outside is definitely desirable. Having the ability to ingest iCalendar could also be a way to implement a show schedule without a whole scheduling app.

**Comment by echarlie** [comment]
Honestly, this should be a google calendar that we publicly share (with heavy links back-and-forth from #358 events), or a seperate service. closing.
