### ISSUE TITLE
"Donate Online" should blink during radiothon

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#28]
Add a config option to toggle whether or not the link at the top is blinking. If blinking, the text color should alternate between gray (what it is now) and red (which happens on hover).

**Comment by matthazinski** [comment]
Apparently the blink tag is deprecated and CSS animations are the new alternative: 

https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_animations

**Comment by mutantmonkey** [comment]
I think this is going to be extremely annoying is going to distract from the rest of the site. I suggest a more subtle animation that still draws attention without completely distracting people.

**Comment by mutantmonkey** [comment]
We have a very noticeable link that seems to work well. Blinking is unnecessary.
