### ISSUE TITLE
Users report that when checking {vinyl,new} in search result, then editing something (say rotation), box unchecks

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#284]
but the users couldn't be bothered to file a bug report.

**Comment by echarlie** [comment]
Just ran a bisect:
53cf9e84fadc60d8eda8cdab9b7d6fdfba47c745 is the first bad commit

**Comment by echarlie** [comment]
okay. rebisected. correctly, this time, I think.
1b7c6b7b8d8155f57ecefa34a32ab33a846aaa1a is the first bad commit

**Comment by mutantmonkey** [comment]
I believe this happens when a search is in progress. My initial idea at a fix is to have a click event on the search results area that cancels any current search.

**Comment by echarlie** [comment]
this is resolved in 06fe15bf42abaad596596491e92b0ca25e773510
