### ISSUE TITLE
when typing in trackman fields, exactly what you want appears in autocomplete, then almost instantly disappears when you move the mouse.

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#285]

**Comment by mutantmonkey** [comment]
We don't have any mouse move events for autocomplete, so something else is at play here.

**Comment by mutantmonkey** [comment]
I think the issue is again that searches are not completing in time and DJs are starting to move their mouse to select something. A potential fix for this is to cancel any pending autocomplete timers (and maybe API calls too).

**Comment by mutantmonkey** [comment]
This should be fixed in 06fe15bf42abaad596596491e92b0ca25e773510.
