### ISSUE TITLE
Underwriting and PSAs should be in Trackman DB

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#29]
It would be useful if Sales/PR staff could have a tool to update a table of PSAs and underwriting that should be read. In trackman, the user should have a highlighted item in their play queue indicating the text of the underwriting or PSA that should be read if this traffic has not yet been read and it is within the segment of the program clock.

**Comment by matthazinski** [comment]
This will have other dependencies, including a multi-computer display of trackman (so one screen can be used for tracklogging and another can be used as a teleprompter-like display)

**Comment by mutantmonkey** [comment]
Also see #294

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#34
