### ISSUE TITLE
"Mic break" button

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#294]
We've previously discussed air logging, but honestly, that might be more complicated than we really need. I don't really want us to put people in a position where they can play "DJ police," so instead, we might want to consider just a single "Mic break" button that logs a mic break in the playlist and updates the RDS and stream metadata accordingly.

This would also allow DJs go on-air before logging a track.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#13
