### ISSUE TITLE
"published" checkbox on pages

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#3]
Currently only articles have the "published" option. It would be nice if pages supported drafts as well.

**Comment by matthazinski** [comment]
Moving to v2.0 since this isn't needed right now and it requires changing the schema.

**Comment by bkodres93** [comment]
One PR for both this and https://github.com/wuvt/wuvt-site/issues/157

PR:
https://github.com/wuvt/wuvt-site/pull/168
