### ISSUE TITLE
File upload support

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#30]
Currently the only way to upload files is from the CIFS share. It would be helpful if we had a way for people to do this online.

**Comment by telnoratti** [comment]
We may have luck finding a flask media manager that acts like a file browser. It could just use our existing users.

**Comment by matthazinski** [comment]
Implemented in https://github.com/wuvt/wuvt-site/commit/2111cbb507e99f2743145109b55b6872fc8589d6
