### ISSUE TITLE
Automation should submit traffic to trackman

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#31]
Whatever we're using for automation (mpd or airtime) needs to submit metadata of traffic pieces to the new website. This should be stored in a table so we can:
- Audit whether or not certain traffic gets played (e.g. figure out how many times per week a PSA gets played and ensure we fulfill underwriting obligations)
- Tie into the queue in trackman for DJs so DJs will constantly get reminded to read traffic until it is marked as complete, either by automation or by the DJ.

**Comment by telnoratti** [comment]
Is there a way to cross link this issue with an issue in automation?

**Comment by telnoratti** [comment]
Automation currently submits this information and trackman recognizes it, but it doesn't process it.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#35
