### ISSUE TITLE
Should be possible to "preload" users into RBAC

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#311]
To handle non-WUVT-auth users especially, it would be nice to "preload" users into trackman/wuvt-site's auth database so that they can be assigned to a group. This is a pre-requisite for putting auth on missioncontrol, unless we can configure wuvt accounts for all DJs

**Comment by mutantmonkey** [comment]
Put them in a group. I don't think it's appropriate for us to deal with this scenario; if your OIDC provider can't return groups for a particular user, that's not our problem.

In our case, I don't really think it's appropriate for us to support these extra login sources. Everyone should just get a WUVT account that needs login. Ultimately, I don't think it makes any sense to support login for mission control given the current use case, so I think that underlying issue mentioned here is invalid.
