### ISSUE TITLE
Improve DJ-facing track editing

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#318]
Now that track matching is case insensitive, DJs may want to correct typos they made when entering the track name. We should decide on how best to do this; two ways that come to mind are:

* Allow any change be to made to a track if we're the only DJ who has ever played it
* Allow case changes to be made by any DJ for any track
* Add an "editors" role that DJ users can be assigned to that allows any track to be edited

We could implement one of these, both, or come up with another solution depending on what we determine is best.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#14
