### ISSUE TITLE
File uploader should set appropriate permissions

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#32]
Ensure files made on the CIFS share and via the upload utility can read/write each other.

**Comment by matthazinski** [comment]
Moving to v1.2 because we'll need to be onsite to test

**Comment by mutantmonkey** [comment]
Is there an action item for this or can this can be closed?

**Comment by echarlie** [comment]
I'm closing this, since I'm pretty sure permissions are set appropriately on nfs.
