### ISSUE TITLE
Provide "comment" field for TrackLog entries

### ISSUE THREAD

**Issue by mutantmonkey** [wuvt/wuvt-site#321]
We should provide an optional "comment" field to go along with TrackLog entries. DJs would be able to use this freeform text field to identify their "song of the week" or go along with particular themes, especially during Radiothon.

DJs have not requested this, and some have even said they didn't want such a feature when asked about it, but it's clear from their actions that this is something that they'd like to have.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#42
