### ISSUE TITLE
Trackman should have a "Help" button

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#33]
This should open a pop up window asking for bug information. I'm not sure how it should be delivered, perhaps the listserv?

**Comment by matthazinski** [comment]
Why in trackman and not the admin panel?

**Comment by telnoratti** [comment]
Not everyone who has access to trackman has access to the admin panel.

**Comment by matthazinski** [comment]
Trackman is restricted to a certain IP range though so people wouldn't be able to file issues remotely, which is a problem.

**Comment by telnoratti** [comment]
Well putting it on the admin panel wouldn't fix that. This shouldn't be the only venue for bug reporting. It would be very useful for a DJ who discovers a bug to submit the report while they're doing their show. Given the propensity of some of our DJs to not report issues, I think this would be the best way to put training wheels on reporting bugs.

Also it should definitely go to bugzilla now that I think about it. We could simply open a new  bug page on that.

**Comment by telnoratti** [comment]
With bugzilla inaccessible, this won't be able to launch this until later.

**Comment by mutantmonkey** [comment]
This should be "Help," not "Report Bug." I'm not convinced DJs will actually use this either.

**Comment by echarlie** [comment]
this is a jira-integration feature. perhaps use a jira issue collector?

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#3
