### ISSUE TITLE
Allow deletion of tracks in last 15 (last 15 should better reflect edits)

### ISSUE THREAD

**Issue by Giggybyte** [wuvt/wuvt-site#354]
There's a potential discrepancy in timestamps/tracks between a DJ's playlist and the last 15 tracks if the DJ deletes/edits tracks. This could be a new issue since multiple DJs have encountered it recently?

**Comment by echarlie** [comment]
I think we discussed and came to the conclusion that a partial cause of this was the logging computer's time being substantially out-of-sync, no?

**Comment by Giggybyte** [comment]
Yes, you're correct -- this issue was made before we discovered that though
:p

**Comment by mutantmonkey** [comment]
Last 15 does reflect deletions and edits.
