### ISSUE TITLE
RFE: Reverse sort order for shows "by DJ"

### ISSUE THREAD

**Issue by echarlie** [wuvt/wuvt-site#384]
From Dr. Sue:

> am I more likely to look at a show from 1 year ago OR one from last week? Now think about Linda, who has been doing this for YEARS & YEARS.  Imagine how many minutes of scrolling she has to do to see the playlist from her most recent show?  (I know, I know .... the system has only had this feature since circa 2014, but you get my point.  Just a thought & not urgent.  (Ten years from now, I will consider it urgent but not now!)

c.f. #301

**Comment by mutantmonkey** [comment]
wuvt/trackman#152 changed the Trackman API to return DJSetst in descending order. However, the playlists_dj_sets.html template does its own grouping by year, which is currently in ascending order. That will need to be changed as well to close this.

I haven't tested this, but I believe that simply adding a `reverse` filter after the `groupby` filter will take care of this.
