### ISSUE TITLE
LDAP auth

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#4]
Would be nice if we used our LDAP server as the auth backend rather than the postgres DB. 

Depends on:
- Migrating users (and setting new LDAP passwords)
- LDAP group for people able to edit the website
- LDAP server being moved to new static DHCP lease
- Test LDAP backups and redeployment of LDAP server

**Comment by matthazinski** [comment]
Update: this should use Flask's loginmanager and LDAP directly. LDAP support should be configurable so that there's the option to disable it if LDAP breaks and fallback to SQL users.

**Comment by mutantmonkey** [comment]
I finished the prep work of cleaning up auth and started some basic work on this and realized we're going to have to import LDAP users into the DB so articles, since they need to have user data associated with them. https://github.com/ContinuumIO/flask-ldap-login looks promising for this.

**Comment by mutantmonkey** [comment]
With 2c92557c0a97409f20360d027260f54fa4bcef98, I have completed most of the framework necessary for LDAP.

I still need to implement STARTTLS and do some testing, then I can hopefully merge this into master.

**Comment by mutantmonkey** [comment]
I forgot to create a merge commit, but this is done.
