### ISSUE TITLE
Remove empty playlists periodically

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#41]
If a playlist with 0 songs in it has existed for more than a day, it should be removed.

**Comment by mutantmonkey** [comment]
How do you envision this working? Do you want to have a script that's called via cron or something?

**Comment by telnoratti** [comment]
I imagine a cronjob script that looks only at playlists older than a day would work. In /trackman/api/search there is a join line that could be pretty handy for this.

**Comment by telnoratti** [comment]
Since we have it now, this should be made as a celery task.

**Comment by matthazinski** [comment]
:+1:

**Comment by mutantmonkey** [comment]
#128 was filed as a dupe of this, which I implemented in aed25fa9795cd6d7686ba58acd1a01080c3b19ea.
