### ISSUE TITLE
Icons on last15 don't always display until refresh

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#47]
Could be an issue with the AJAX loader trying to load the icons as if they were HTML.

**Comment by telnoratti** [comment]
It appears to work fine for me, could you give steps to reproduce and browser info?

**Comment by matthazinski** [comment]
Open https://www.wuvt.vt.edu/last15 in a new tab in the latest Chromium. It doesn't show any icons until you refresh.

**Comment by telnoratti** [comment]
Fixed in e1a5aaace8efa353c1f818716ae1cf872c9ee6cb. @matthazinski can you verify?

**Comment by telnoratti** [comment]
Verified by @andreimarcu.
