### ISSUE TITLE
DJs should be able to set bio and page content in trackman

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#49]
DJ pages already exist in the playlists tool. Why not allow them to add an arbitrary markdown section at the top of the page?

**Comment by telnoratti** [comment]
Not sure this is reasonable for the 1.2 milestone. It might be best to target only minor and critical changes to the site for 1.2 and push changes like this to 1.3.

**Comment by matthazinski** [comment]
Moved to v1.3.

**Comment by mutantmonkey** [comment]
DJs may also want the ability to rename their show.

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#4
