### ISSUE TITLE
Weekly charts should exist in 'playlists' menu

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#50]
There should be a page under 'playlists' that has:
* A link to last.fm
* Top 10 new tracks this week (by non-automation spins)
* Top 10 artists this week (by non-automation spins)
* Top 10 new albums this week (by non-automation spins)

**Comment by telnoratti** [comment]
Should this page have static content that is updated when the new chart is calculated?

**Comment by matthazinski** [comment]
I'd prefer to do it dynamically over the past 7 days.

**Comment by telnoratti** [comment]
Agreed that makes more sense.

**Comment by matthazinski** [comment]
See the query in #38 for implementing
