### ISSUE TITLE
Schedule should not be an image

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#51]
This creates serious usability problems. I want the ability to click on sections of a table to link me to a DJ's page. (e.g. http://www.wuvt.vt.edu/playlists/dj/7).

**Comment by telnoratti** [comment]
We need Ben Jaques on github. This seems like an issue for him.

**Comment by matthazinski** [comment]
:+1:

**Comment by telnoratti** [comment]
#49 is related as the schedule should eventually link to DJ pages.

**Comment by mutantmonkey** [comment]
It's a Google Calendar now.
