### ISSUE TITLE
Current track banner should link to a DJ's playlists page 

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#53]

**Comment by mutantmonkey** [comment]
How should this work for automation and other DJs not marked as visible, should it just not create a link?

**Comment by matthazinski** [comment]
I believe automation will be the only invisible DJ. But yes, that sounds appropriate.

(I'd like to eventually have automation playlists be visible, but that's another issue)

**Comment by mutantmonkey** [comment]
This could get ugly.
