### ISSUE TITLE
Copyright statement below side navbar

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#55]
Let's use something like CC NC-SA for website content, a free license for website source code, and a CC NC-ND license for for site templates (to discourage ads).

**Comment by mutantmonkey** [comment]
If we can, I'd like to do GPLv3 for the source code, but I'm not sure it's possible to combine that with CC NC-ND.

**Comment by matthazinski** [comment]
I don't believe those are compatible. How about the Apache License?

**Comment by mutantmonkey** [comment]
Yeah, that's fine I suppose.
