### ISSUE TITLE
Trackman 'email me my playlist' reported to be nonfunctional

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#57]

**Comment by telnoratti** [comment]
This is almost certainly caused by email not working.

**Comment by matthazinski** [comment]
Sledge is able to relay mail from fukushima, so it's a website problem. Reassigning.

**Comment by telnoratti** [comment]
=(

**Comment by telnoratti** [comment]
This always attempts to email the playlist currently.
