### ISSUE TITLE
DJs marked as not visible should not show up in by date

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#58]
Namely automation is showing up in by date. 
![capture](https://cloud.githubusercontent.com/assets/599870/6538927/cecf7f92-c436-11e4-80c0-d214acd76418.PNG)

**Comment by matthazinski** [comment]
Why shouldn't they be visible?

**Comment by telnoratti** [comment]
ea6d33cd3ae77995eed0dfc77e98a7a022b0a178 put the groundwork in place for this now
