### ISSUE TITLE
Log automation playlists like normal DJs

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#62]
A DJ logging out should trigger starting an automation playlist; logging in should end the playlist. This would enable automation playlists to be tracked rather than have to be marked as 'hidden'.

**Comment by mutantmonkey** [comment]
This is going to be a little bit tricky because the script that sends the automation metadata won't know which playlist to associate it with. This will have to be determined at track submission by Trackman.

**Comment by telnoratti** [comment]
This shouldn't be a DJ logging out, but the activation of automation that triggers this. Related to #58
