### ISSUE TITLE
API for non-automation DJs to interface with trackman

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#63]
It would be awesome if DJs had a way to programatically interface with trackman (e.g. for those that use MPD on their shows).

Things to support:
- Search (see #102) - return data from ALL metadata sources that trackman knows about, or allow the requester to choose a specific one. 
- Login (not to be confused with auth) - stops automation as the metadata source if it is active and logs in the DJ. If a DJ is already logged in, it returns an error instead. Requestor must give DJ ID number so Trackman knows who to login.
- Force login - same as login, but also logs out the current DJ if there is one
- Logout - logs out the current DJ
- Get current DJ
- Send metadata - just like our automation setup, but DJ ID should be sent in the request. If the DJ corresponding to the DJ ID is not currently logged in, do nothing. Something should be returned letting the user know whether or not the update went through. 

We'll have to decide on API keys later. For the time being, just restrict to local subnets.

The end goal here is: 

1. Allow power users to send metadata more efficiently while doing shows
2. Remote programatic access to the airchain to break-in whenever automation is on/no one is present at the station. This would allow fixing audio in the event of some sort of emergency or equipment failure. I'm thinking something like JACK on the automation PC allowing switching between MPD and OpenOB. (This is a separate project).

**Comment by telnoratti** [comment]
Very much so! I could automate my entire show!

**Comment by mutantmonkey** [comment]
There is no work to be done here. This is how Trackman works. A potential area of future improvement is support for authentication while outside of the WUVT network, but this should be in a separate ticket entirely.
