### ISSUE TITLE
Markdown fonts should be standardized

### ISSUE THREAD

**Issue by telnoratti** [wuvt/wuvt-site#64]
This can cause rendering issues for various things.
![e50xh6npk](https://cloud.githubusercontent.com/assets/599870/6540621/f83bfd26-c475-11e4-9bfc-5f16632113e1.png)

**Comment by telnoratti** [comment]
I think this will need to be done in css. Blanket picking a font for all markdown content should fix it.

**Comment by telnoratti** [comment]
@mutantmonkey suggests that this could alternatively be fixed by adding 
```
clear:left
```
to the img element style

**Comment by mutantmonkey** [comment]
This is an issue with floats, not fonts.
