### ISSUE TITLE
Custom HTTP 500 error page

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#65]
It should have a WUVT theme and indicate wuvt.vt.edu is down for scheduled maintenance, with links to the stream.

Suggested: image of robot pouring coffee into himself

**Comment by telnoratti** [comment]
:+1:

**Comment by matthazinski** [comment]
Self-assigning because our art director doesn't github.

**Comment by mutantmonkey** [comment]
We probably want to cover all 50x errors, like 504 for example. We can use the same image.

**Comment by mutantmonkey** [comment]
When can we expect the image to be ready? If it's going to take a while, I could potentially make something without images for now.

**Comment by mutantmonkey** [comment]
Do we have an ETA yet?

**Comment by matthazinski** [comment]
Assiging telnoratti to nag the art director. It's only been 8+ months, I'm sure she'll get to it shortly. :unamused:

**Comment by mutantmonkey** [comment]
So is this going to happen or not?

**Comment by matthazinski** [comment]
@echarlie can you nag the appropriate person?

**Comment by mutantmonkey** [comment]
I am not expecting this to actually happen at this point, so I will come up with a text-only version of this.
@echarlie Please nag the art director anyway. It's pretty ridiculous that we've been blocked on this for over a year.
