### ISSUE TITLE
Archive.org playlist link broken for http://www.wuvt.vt.edu/playlists/set/7

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#69]
http://www.wuvt.vt.edu/playlists/set/7

But the airchecks definitely exist: https://archive.org/details/WUVTFM_2015030521

He somehow managed to start his playlist after ending it (2015-03-05 21:06-2015-03-05 19:14) - I'm guessing this is an issue we caused when changing timezones?

**Comment by telnoratti** [comment]
This is. I'll just edit his dtstart.

**Comment by telnoratti** [comment]
Fixed.
