### ISSUE TITLE
First track in old playlist is sometimes the currently playing track

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#71]
![Example](https://i.imgur.com/IBIMt5M.png)

If you refresh, the problem goes away until the currently playing track changes.

**Comment by telnoratti** [comment]
I would guess last15 code is running on the playlists.

**Comment by mutantmonkey** [comment]
Oh, I didn't realize there was already an issue filed; I fixed this in e7e296404e040f8a6d42eeba3e5d915b97d2a1ab.
