### ISSUE TITLE
Archived DJs section on /playlists/dj

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#77]
On the playlists by DJ section, shows which have not aired in the past 12 months should be moved to a separate section so it's easier to find DJs on the current schedule. If a DJ does a sub show, he should be moved to 'current'.

**Comment by mutantmonkey** [comment]
Implemented the same functionality Quicktrack had in 3c7fda4be035a2cfa165f6532f162d69124f9f6e by using the visible attribute. Please reopen if this is not to your satisfaction, but I think automatically archiving DJs is not ideal.
