### ISSUE TITLE
DJs should have a show name field in trackman

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#78]
A better unique identifier for trackman users is show name rather than DJ name, as DJs may want to have multiple shows with different themes. We should also enforce uniqueness for show name.

**Comment by telnoratti** [comment]
This probably depends on an interface to edit your DJ information since there are already entered DJs. I'm not sure how the relation between show name and DJ should be with respect to logging into a site. Would I login as the DJ, then select the show to play?

**Comment by matthazinski** [comment]
No, you would login as a show.

**Comment by telnoratti** [comment]
So every time I want to do a new show I would register a new DJ?

**Comment by matthazinski** [comment]
Yes, with the assumption that a schedule spot would always correspond to the same show (assuming the DJ shows up)

**Comment by telnoratti** [comment]
Okay sounds good, maybe we should change some of the wording to reflect that they're creating a show, not a DJ. For example instead of "Register DJ" say "Register Show"

**Comment by telnoratti** [comment]
Should we use DJ name for anything? I assume people still want to be known by their DJ name.

A list of everywhere in the code as of c1e539fc5 this shows up and needs to be considered.
```
./wuvt/trackman/lib.py:40:    msg['To'] = djset.dj.email
./wuvt/trackman/lib.py:45:        djname=djset.dj.airname,
./wuvt/trackman/views.py:30:        data['dj'] = dj.airname
./wuvt/trackman/views.py:33:        data['dj'] = track.djset.dj.airname
./wuvt/templates/trackman/log.html:10:        <h1>{{ trackman_name }}: {{ djset.dj.airname }}</h1>
./wuvt/templates/trackman/edit.html:6:        <h1>Edit Track: {{ track.djset.dj.airname }}</h1>
./wuvt/templates/trackman/login.html:13:            <option value="{{ dj.id }}">{{ dj.airname }}
./wuvt/templates/email/playlist.txt:1:Your playlist: {{ djset.dj.airname }} / {{ djset.dtstart|datetime("%Y-%m-%d %H:%M") }}
./wuvt/templates/email/playlist.html:5:    <title>Your playlist: {{ djset.dj.airname }}</title>
./wuvt/templates/email/playlist.html:8:    <h1>Your playlist: {{ djset.dj.airname }} /
./wuvt/templates/playlists_dj_sets.html:2:{% block title %}{{ dj.airname }} - Playlist Archive (by DJ) - {{ super() }}{% endblock %}
./wuvt/templates/playlists_dj_sets.html:8:    <h3>{{ dj.airname }}</h3>
./wuvt/templates/last15.html:31:                {% if track.dj.visible -%} 
./wuvt/templates/last15.html:32:                <a href="{{ url_for('playlists_dj_sets', dj_id=track.dj_id) }}">{{ track.dj.airname }}</a>
./wuvt/templates/last15.html:34:                {{ track.dj.airname }}
./wuvt/templates/playlist.html:2:{% block title %}{{ djset.dtstart|datetime("%Y-%m-%d %H:%M") }} - {{ djset.dj.airname }} - Playlist Archive - {{ super() }}{% endblock %}
./wuvt/templates/playlist.html:10:    <h3>{{ djset.dj.airname }} / {{ djset.dtstart|datetime("%Y-%m-%d %H:%M") }}</h3>
./wuvt/templates/playlists_date_sets.html:14:        <li><a href="{{ url_for('playlist', set_id=set.id) }}">{{ set.dtstart|datetime("%H:%S") }}-{{ set.dtend|datetime("%H:%S") }} {{ set.dj.airname }}</a></li>
./wuvt/templates/playlists_dj_list.html:13:        <li><a href="{{ url_for('playlists_dj_sets', dj_id=dj.id) }}">{{ dj.airname }}</a></li>
```

**Comment by matthazinski** [comment]
I just realized not everyone has a show name. Maybe we should support a blank show name field and show the DJ name field instead in that case?

**Comment by telnoratti** [comment]
What about playlist by DJ or by Show? DJs may want to change their show e.g. from Americana to Metal. Changing the show name will have lots of playlists listed under that show name.

**Comment by matthazinski** [comment]
Moving to 'maybe' since I'd like to hash out the design more before starting

**Comment by echarlie** [comment]
This issue was moved to wuvt/trackman#5
