### ISSUE TITLE
Link/icon to last.fm on sidebar

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#90]

**Comment by matthazinski** [comment]
Self-assigning because art director doesn't github

**Comment by mutantmonkey** [comment]
We could also go with a text link on the playlists page, or both that and this. Thoughts?

**Comment by telnoratti** [comment]
I think there should be an icon at the very least. Where would the link go?

**Comment by mutantmonkey** [comment]
"Missed a song?" section on the last 15 tracks page is one place it could go.

**Comment by matthazinski** [comment]
Just refreshed the page without adblock, I agree. Does libre.fm have feature parity?

**Comment by telnoratti** [comment]
I think more people use last.fm than libre.fm. We could simply list libre first every time we list the two, but I'm not sure we should forgo displaying last.fm.

**Comment by mutantmonkey** [comment]
Definitely display both if we're going to display one. I mainly see last.fm and libre.fm as publicity with some nice reporting features built in, so I don't think we need to make the links for these particularly prominent.

**Comment by matthazinski** [comment]
Closing WONTFIX.
