### ISSUE TITLE
"Flag" link on playlist page

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#91]
Each track in a playlist should contain a "flag" link to allow you to report an entry to one or more people (e.g. MD, FMPD, DJ, TD, CE) by selecting from a drop-down list of various reasons (e.g. bad metadata, bad music, bad sound quality, FCC violation).

**Comment by mutantmonkey** [comment]
I think this is going to complicate the UI too much, and it shouldn't be the responsibility of the visitor or listener to ensure WUVT has things together.

**Comment by matthazinski** [comment]
Maybe we can whitelist IPs like trackman does?

**Comment by matthazinski** [comment]
Better yet, instead of emails, let's use Twilio to direct complaints to the request line.

**Comment by andreimarcu** [comment]
:+1:

**Comment by mutantmonkey** [comment]
This is a dupe of #74.
