### ISSUE TITLE
Nightly backups

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#92]
Do this nightly:
- mysqldump to offsite storage
- rsync of /srv/http/media offsite

**Comment by telnoratti** [comment]
mysql backups to arrit are done, is all of /mnt/mckillican/bak being backed up offsite?

**Comment by matthazinski** [comment]
All of /mnt/mckillican should be backed up to offsite nightly, but please confirm.

**Comment by telnoratti** [comment]
I confirmed this is not happening, what is the IP of the offsite backup?

**Comment by matthazinski** [comment]
172.16.84.152 on the ECE network

**Comment by matthazinski** [comment]
@telnoratti , is this happening?

**Comment by echarlie** [comment]
this is an infra issue. closing for irrelevance
