### ISSUE TITLE
Playlists by date doesn't show in-progress shows

### ISSUE THREAD

**Issue by matthazinski** [wuvt/wuvt-site#93]
e.g. http://wuvt.vt.edu/playlists/date/2015/03/11 is missing http://wuvt.vt.edu/playlists/set/29 currently.

**Comment by mutantmonkey** [comment]
Closing this, it's no longer valid.

**Comment by mutantmonkey** [comment]
On second thought, those pages still work, so I'll go ahead and fix this. This is largely irrelevant with the new playlists by date page though.
